[build]
  command = "bundle exec jekyll build --baseurl '' && mkdir -p _site/admin && cp admin/index.html admin/config.yml _site/admin/"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.3.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"
